### PR TITLE
Set outline on focused radiobutton

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
### ☑️ Resolves

* Fix https://github.com/nextcloud/server/issues/39413

Outline idea was taken from https://github.com/nextcloud/nextcloud-vue/issues/4193

### 🖼️ Screenshots

🏚️ Before
Peek 2023-07-17 10-35

🏡 After
Peek 2023-07-19 09-25

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
should be done for master too

**Review by Pytal — APPROVED** [review]

**Review by susnux — APPROVED** [review]
:sparkles:

**Review by marcoambrosini — CHANGES_REQUESTED** [review]
I don't think we should have this. Te radio button should display the double outline only when focused via keyboard like in `NcButton`. This pr shows the outline on them when hovered and focused.
cc @nextcloud/designers 

Current state as per this pr: 

https://github.com/nextcloud/nextcloud-vue/assets/26852655/a245f28b-8073-4ea6-beb9-41d30c58f293

**Comment by JuliaKirschenheuter** [comment]
Thank you @marcoambrosini 
Then i will leave background color (as we had it already) and will set a double outline only on focus, right?

**Comment by nimishavijay** [comment]
With this change, the outline is still seen when you click on an item (screenshot attached), which is not ideal. It should be shown only for keyboard navigation, similar to the conversation list in Talk. Would that be possible? :) 


https://github.com/nextcloud/nextcloud-vue/assets/52440189/44e04534-4081-4aaf-b7dc-f1d301029c39

**Comment by Pytal** [comment]
> With this change, the outline is still seen when you click on an item (screenshot attached), which is not ideal. It should be shown only for keyboard navigation, similar to the conversation list in Talk. Would that be possible? :)

`:focus-visible` ?

**Comment by marcoambrosini** [comment]
Yes `:focus-visible` @JuliaKirschenheuter

**Comment by marcoambrosini** [comment]
You're right @JuliaKirschenheuter, there's no focus state on radio buttons.

So I would drop this outline altogether here as it's not an accessibility requirement.
In this case we have the filled circle already indicating the selected state of the radio button.

**Comment by JuliaKirschenheuter** [comment]
> In this case we have the filled circle already indicating the selected state of the radio button.

@marcoambrosini we have to mark selected radio button, see an example under: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Peek 2023-07-24 15-49

> there's no focus state on radio buttons.

i will try to set `:focus-visible` on a label after my vacation

**Comment by JuliaKirschenheuter** [comment]
I will finish this PR after my vacation

**Comment by marcoambrosini** [comment]
Ok, I see. So it is possible to differentiate between keyboard and mouse navigation. Can we have a coworking call to get to the bottom of this @JuliaKirschenheuter when you're back? 
Happy holidays 🌴 😄

**Comment by JuliaKirschenheuter** [comment]
After updating Nc Vue to ^8.0.0 and component refactoring focus / hover / selected state looking good ;)
Thanks @susnux!

How it look s now:

Peek 2023-08-11 11-05

Closing PR because not relevant anymore

**Pull request closed without merging**
