### PR TITLE
Harmonize focus-visible styles for vue-navigation item with none-vue navigation item

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
### ☑️ Resolves

* For https://github.com/nextcloud/server/issues/41699

**Before 
Vue-navigation** 

Peek 2024-01-03 15-44

**Unchanged non-vue navigation**

Peek 2024-01-03 15-31

**After
Vue-navigation** 

Peek 2024-01-03 15-30

Vue-navigation | Unchanged non-vue navigation
---|---
Screenshot from 2024-01-03 15-31-17 | Screenshot from 2024-01-03 15-31-12

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
Tested on my local dev env - LGTM :) really nice change, good for a11y

**Review by emoral435 — CHANGES_REQUESTED** [review]
Actually, I found something that looks broken - this is for the subitems beneath the shared files section here:
image
the border-radius may have to be increased, or due to the shift padding/margin on the submenu files in shared (and also probably the favorites section...) this has to be changed before it gets merged.

**Comment by JuliaKirschenheuter** [comment]
> Actually, I found something that looks broken - this is for the subitems beneath the shared files section here: the border-radius may have to be increased, or due to the shift padding/margin on the submenu files in shared (and also probably the favorites section...) this has to be changed before it gets merged :) sorry to be so nitpicky ;(

Yeah, I've seen it too. But it is actually another issue (which is not relevant for a11y) and is present on master:

Screenshot from 2024-01-04 09-16-08

**Review by Pytal — APPROVED** [review]

**Comment by emoral435** [comment]
> Yeah, I've seen it too. But it is actually another issue (which is not relevant for a11y) and is present on master:
I see then. this is all good to me then!

**Review by emoral435 — APPROVED** [review]

**Pull request merged**
