### PR TITLE
feat(NcActions): focus the first action again if no action have a focus after render

### PR DESCRIPTION
**Pull request by skjnldsv**
From https://github.com/nextcloud/server/pull/41010#pullrequestreview-1717797692

## Testing [in preview ⬈](https://deploy-preview-4775--nextcloud-vue-components.netlify.app/)

```vue
<template>
	<NcActions>
		<template v-if="!showMenu">
			<NcActionButton @click="showMessage('Edit')">Edit</NcActionButton>
			<NcActionButton :is-menu="true" @click="showMenu = true">Show menu</NcActionButton>
		</template>
		<template v-else>
			<NcActionButton key="menu-1" @click="showMenu = false">< Back</NcActionButton>
			<NcActionButton key="menu-2" @click="showMessage('Edit')">Second entries</NcActionButton>
			<NcActionButton key="menu-3" @click="showMessage('Delete')">Second entries</NcActionButton>
		</template>
	</NcActions>
</template>
<script>
export default {
	data() {
		return {
			showMenu: false,
		}
	},
	methods: {
		showMessage(msg) {
			alert(msg)
		},
	},
}
</script>
```

### CODE REVIEW

**Comment by susnux** [comment]
Works here, but for the files app you need to make sure that the focus after clicking "back" is set to the "set reminder" entry and not the first one. (So that after clicking back your focus in on the entry you clicked to open then menu).


https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/f4ff226c-e704-4fb4-b852-9c2e8a718e65

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Works here, but for the files app you need to make sure that the focus after clicking "back" is set to the "set reminder" entry and not the first one. (So that after clicking back your focus in on the entry you clicked to open then menu).

This is a different topic then
I can see two different approaches:
1. We really push the concept of "submenu" here and add dedicated logic
2. We let the dev handle this and use something like `aria-selected` https://github.com/nextcloud/nextcloud-vue/blob/a4326162d29a04ee6d4d8d142ca960323ff816d3/src/components/NcActions/NcActions.vue#L935

I personally vote for `2`, dedicated logic would be to store the ID somewhere, detect that the entire children changed somehow, then focus back the previous ID? Considering the VNodes are different, same as the element, that seems much more complicated to handle.

**Comment by susnux** [comment]
@skjnldsv yes 2 probably. For the text app this is currently done like that (we use submenus there too so we also needed to fix it). Thats why I wrote it works here but for apps you need to manually keep track of menu changes.

```vue
<template>
	<NcActions>
		<template v-if="!showMenu">
			<NcActionButton @click="showMessage('Edit')">Edit</NcActionButton>
			<NcActionButton ref="menuToggle" :is-menu="true" @click="showMenu = true">Show menu</NcActionButton>
		</template>
		<template v-else>
			<NcActionButton key="menu-1" @click="handleClose">< Back</NcActionButton>
			<NcActionButton key="menu-2" @click="showMessage('Edit')">Second entries</NcActionButton>
			<NcActionButton key="menu-3" @click="showMessage('Delete')">Second entries</NcActionButton>
		</template>
	</NcActions>
</template>
<script>
export default {
	data() {
		return {
			showMenu: false,
		}
	},
	methods: {
		showMessage(msg) {
			alert(msg)
		},
		handleClose() {
			this.showMenu = false
			// Required on this PR to prevent focusing the first entry
			this.$nextTick(() => this.$refs.menuToggle.$el.classList.add('active')
			this.$nextTick(() => this.$refs.menuToggle.$el.focus())
		}
	},
}
</script>
```

**Comment by skjnldsv** [comment]
> ```
> this.$nextTick(() => this.$refs.menuToggle.$el.getElementsByTagName('button')[0].focus())
> ```

A bit simpler :)
https://github.com/nextcloud/server/pull/41338

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
