### PR TITLE
fix: comments box overlapping

### PR DESCRIPTION
**Pull request by solracsf**
### Resolves

Fix https://github.com/nextcloud/nextcloud-vue/issues/2027

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by ShGKme — COMMENTED** [review]
I'm not sure this is a good way to fix overlapping. The fix should not change the size of the block.
And it breaks the cursor position in FF fixed by https://github.com/nextcloud/nextcloud-vue/pull/3832

Maybe cut the text in a placeholder with an ellipsis? 

Also, the default placeholder is truly too long now with `:`, `@`, and `/` commands. Maybe we can make it shorter or display it not in the placeholder.

**Comment by solracsf** [comment]
Yeah, that PR introduced this.
https://github.com/nextcloud/nextcloud-vue/issues/3853

Text can be cutted of since there are essential informations on it. But, another way would be to:
- Put a small text as placeholder like `New comment`
- and on mouse hover or similar, git all that info about `:`, `@`, and `/` commands

**Review by szaimen — APPROVED** [review]
Good from my side

**Comment by solracsf** [comment]
Closing after https://github.com/nextcloud/server/pull/40294

**Pull request closed without merging**
