### PR TITLE
feat: add github changelog generator

### PR DESCRIPTION
**Pull request by skjnldsv**
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

### CODE REVIEW

**Comment by skjnldsv** [comment]
I think we'll have to merge to try! :shrug: :see_no_evil:

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
We could keep the old one as long as the new one is experimental

**Comment by skjnldsv** [comment]
> We could keep the old one as long as the new one is experimental

It's kinda taking forever and failing half the time :/
I've been using github's changelog and manually formatting for months now :)

**Comment by skjnldsv** [comment]
Works, but it does show we're not good at setting labels
image

**Comment by skjnldsv** [comment]
Much better

image

**Pull request merged**
