### PR TITLE
NcListItem: make the max width of the NcListItem in oneline mode apply only to the content name

### PR DESCRIPTION
**Pull request by GVodyanov**
### ☑️ Resolves

- Fix https://github.com/nextcloud/mail/issues/10086

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Screenshot from 2024-09-02 16-30-31 | Screenshot from 2024-09-02 16-31-48

### CODE REVIEW

**Review by susnux — APPROVED** [review]
looks good to me for the one line design :+1:

**Review by GretaD — APPROVED** [review]
i tested it by adding the values on web console and not linking :) #sorry

**Comment by susnux** [comment]
Please remember to set the labels correctly they are needed for changelog generation (bug, enhancement, refactor) :)

**Pull request merged**
