### PR TITLE
fix(NcAvatar): Increase contrast of avatar status icon

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/server/issues/41856

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image
image | image
image | image

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
On light theme:

image

**Comment by ShGKme** [comment]
Doesn't it seem a bit too contrast on the light theme?

image

Dark | Light
---|---
image | image

**Comment by susnux** [comment]
Is it the contrast of the icon to the background? I read the issue as if the color of the status indicator does not have enough contrast meaning the green on the white.

**Comment by szaimen** [comment]
> So we should maybe adjust the SVGs for the status icons (and use the --color-success etc variables, this this possible?) as the our variables are tested to have high enough contrast.

yeah, this would be good if this fixes the problem :)

**Review by susnux — APPROVED** [review]

**Comment by ShGKme** [comment]
Remember to add `enhancement` label for new features and `bug` for fixing bugs, including accessibility or adjustments 😀

**Pull request merged**
