### PR TITLE
chore: prepare v9.0.0 alpha.1

### PR DESCRIPTION
**Pull request by Antreesy**
## [v9.0.0](https://github.com/nextcloud-libraries/nextcloud-vue/tree/v9.0.0-alpha.0) (unreleased)
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.0...v9.0.0-alpha.1)

### 🐛 Fixed bugs
* fix(NcAppSidebar): adjust animation class names by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5168
* fix(docs): bring back NcAppSidebar in docs by @raimund-schluessler in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5167

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
@Antreesy Thanks a lot! We should probably also wait for #5178 and #5179 and the respective backports, so `next` includes everything from `master`.

**Comment by Antreesy** [comment]
> We should probably also wait

Of course, I won't rush here

**Comment by raimund-schluessler** [comment]
Requires #5184.

**Comment by susnux** [comment]
Would like to see https://github.com/nextcloud-libraries/nextcloud-vue/pull/5068 in, but someone has to review ^^
If not lets do the alpha.1 without

**Review by susnux — APPROVED** [review]

**Comment by Antreesy** [comment]
Don't forget to include missing entry in 8.6.0: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5192 (for me or whoever will rebase)

**Comment by raimund-schluessler** [comment]
> > Don't forget to include missing entry in 8.6.0: #5192 (for me or whoever will rebase)
> 
> See #5193

It is #5195 now. Review and merge it fast, before there are more commits to `master` 🙂🙈

**Comment by susnux** [comment]
> Review and merge it fast, before there are more commits to master 🙂🙈

Done so only this needs to be reviewed :)

**Review by raimund-schluessler — APPROVED** [review]

**Comment by Antreesy** [comment]
My draft was lost, so prepared and published a new one: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v9.0.0-alpha.1

**Pull request merged**
