### PR TITLE
try to fix header size on mobile

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/server/issues/39881

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by szaimen** [comment]
cc @nimishavijay @jancborchardt @marcoambrosini

**Review by jancborchardt — APPROVED** [review]
Seems to work to give a bit more space, nice!

**Review by AndyScherzinger — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by szaimen** [comment]
btw, does the backport bot work here?

**Comment by susnux** [comment]
> btw, does the backport bot work here?

good question, before the migration yes but maybe @skjnldsv or @nickvergessen can help?

**Comment by szaimen** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4421

**Comment by skjnldsv** [comment]
Unfortunately the bot is scoped under the @nextcloud org :/

**Pull request merged**
