### PR TITLE
Feat(NcAppContent) Add horizontal split for appcontent

### PR DESCRIPTION
**Pull request by GretaD**
### ☑️ Resolves

- Ref https://github.com/nextcloud/mail/issues/8309

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Comment by GretaD** [comment]
Right now it looks like this, without the splitpane line. I added a class for that and i style it but it doesnt show anything.
Screenshot from 2024-03-13 15-01-48
This is how it should look unless we make the line bigger.
Screenshot from 2024-03-13 15-02-23

I see these classes showing up, but only the horizontal one should be shown actually.
Screenshot from 2024-03-13 15-08-39

**Comment by GretaD** [comment]
Screenshot from 2024-03-14 13-20-59

**Review by ChristophWurst — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Pull request merged**
