### PR TITLE
chore!: Rename `Datetime` to `DateTime` in component names

### PR DESCRIPTION
**Pull request by susnux**
### ☑️ Resolves

Fix inconsistent naming
* `NcDatetime` is now called `NcDateTime` (not yet released to ok)
* `NcDatetimePicker` is now called `NcDateTimePicker` (breaking, but we make it consistent with DateTimeNative)

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by st3iny — APPROVED** [review]
That was quick :smile:

**Review by raimund-schluessler — CHANGES_REQUESTED** [review]
That is inconsistent with the other component names.

**Comment by susnux** [comment]
But what is a *Datetime*? It is a *Date* and *Time* picker so I would say *DateTimePicker* makes more sense.
At least it is more consistent with all other names like *AppNavigation* (and not *Appnavigation*) etc.

**Comment by raimund-schluessler** [comment]
> But what is a _Datetime_? It is a _Date_ and _Time_ picker so I would say _DateTimePicker_ makes more sense. At least it is more consistent with all other names like _AppNavigation_ (and not _Appnavigation_) etc.

I considered datetime to be one word, but that is probably a German bias. I am fine with whatever consistent solution we use. We just have to revert and adjust it for `next` as well then.

**Comment by skjnldsv** [comment]
DateTime is used in javascript
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

**Pull request merged**
