### PR TITLE
[next] fix(NcActionInput): listen to correct events

### LINKED ISSUE #5229: [next] `NcActionInput` does not listen to correct events
No idea how I could have overlooked this, but `NcActionInput` does not listen to the correct events. It still listens to `@change` and `@input` which got replace with `@update:model-value` or simply `v-model`.
I will send a PR later.

### PR DESCRIPTION
**Pull request by raimund-schluessler**
### ☑️ Resolves

* This PR fixes `NcActionInput` to listen to the correct events of its child components. Before, the events of its childcomponents would not trigger an update of the model value.
* Fix #5229

### CODE REVIEW

**Review by ShGKme — COMMENTED** [review]
Makes sense.

I haven't tested, but it looks like `input` and `change` events doesn't work anymore with this PR. As they only proxied the same native events with native `Event` payload, we probably can just remove them from the `emits` declaration to bring them back. (Will work as a part of `v-bind="$attrs"`)

**Review by skjnldsv — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
> Makes sense.
> 
> I haven't tested, but it looks like `input` and `change` events doesn't work anymore with this PR. As they only proxied the same native events with native `Event` payload, we probably can just remove them from the `emits` declaration to bring them back. (Will work as a part of `v-bind="$attrs"`)

@ShGKme I removed them from the `emits` declaration and `@change` and `@input` are emitted now. Unfortunately, they are emitted twice, do you have an idea why? Could this be a problem with `NcTextField`?

**Comment by raimund-schluessler** [comment]
Setting `inheritAttrs: false` for `NcActionInput` might then break things we want, like style or css  no?

**Comment by ShGKme** [comment]
> Setting `inheritAttrs: false` for `NcActionInput` might then break things we want, like style or css no?

Yes, but using `v-bind="$attrs"` without `inheritAttrs: false` is always an issue, it duplicates everything. We can add `class` to `props` as we did in other places to set it on the root.

**Comment by raimund-schluessler** [comment]
> > Setting `inheritAttrs: false` for `NcActionInput` might then break things we want, like style or css no?
> 
> Yes, but using `v-bind="$attrs"` without `inheritAttrs: false` is always an issue, it duplicates everything. We can add `class` to `props` as we did in other places to set it on the root.

Done.

**Review by emoral435 — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Pull request merged**
