### PR TITLE
fix(NcCheckBoxRadioSwitch): do not toggle on a click on a link inside

### PR DESCRIPTION
**Pull request by DorraJaouad**
… a link

### ☑️ Resolves

In rich text > tasks list, check boxes can have links

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
link1| link-2

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]

**Comment by ShGKme** [comment]
But generally speaking, it is not valid to put an interactive element into another interactive element, and it fails a11y check

**Comment by DorraJaouad** [comment]
>  it is not valid to put an interactive element into another interactive element, and it fails a11y check

Agree 🙈 , maybe we need to alter component to be interactive on checkbox level only (at least needed for `NcRichText`)

**Review by Antreesy — APPROVED** [review]
🙈

**Comment by susnux** [comment]
> But generally speaking, it is not valid to put an interactive element into another interactive element, and it fails a11y check

I was thinking the same. Task lists should probably not put the content inside the checkbox (if not only text)

**Pull request merged**
