### PR TITLE
fix(NcAppSidebar): RTL support

### PR DESCRIPTION
**Pull request by hamza221**
### ☑️ Resolves

- Fix https://github.com/nextcloud/calendar/issues/6400

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [x] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Review by Antreesy — COMMENTED** [review]
Looks fine in Talk, if `right` is not defined with another stylesheet
check also for padding-right and padding-left in this file
image

**Review by susnux — APPROVED** [review]

**Comment by hamza221** [comment]
> Looks fine in Talk, if `right` is not defined with another stylesheet check also for padding-right and padding-left in this file image

I was not able to test all the classes on Calendar

**Comment by Antreesy** [comment]
In Files:
image

I was checking missing elements, let me push

**Review by Antreesy — APPROVED** [review]
Tested
image

**Pull request merged**
