### PR TITLE
fix(NcVNodes): add re-export in root export and add docs

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

- For https://github.com/nextcloud-libraries/nextcloud-vue/issues/5662

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

A util component to render a VNode or an array of VNodes from the prop or the default slot.

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Comment by raimund-schluessler** [comment]
Why not. Although we don't even export it in https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/index.js

**Review by raimund-schluessler — APPROVED** [review]

**Comment by ShGKme** [comment]
> we don't even export

Oh... 🥲

**Comment by ShGKme** [comment]
> Although we don't even export it in

Fixed here as well.

In general component has been exported in `/dist/Components`.

**Comment by ShGKme** [comment]
Commit renamed to `fix` with a new export.

**Pull request merged**
