### PR TITLE
Feature: Add visible inner label for `NcInputField`

### LINKED ISSUE #4126: RFC: Visible internal label for `NcInputField`s within the element
I pretty sure this is nothing new, probably someone already uses something like this, but I wanted to know your opinions on this idea:

Having a visual label is most often required, but also often the placeholder is misused for it.
As placeholders should specify what input is correct or expected but not necessarily what field it currently is.

I also noticed that our `NcSelect` does now has a height of 48px vs all other input elements (36px), sometimes this looks odd together so I resize inputs to match the 48px. Which gives 12px extra space.

Combining this two things I came up with the idea to have the label be inside the element and only shrink and move when entering text.

So this is how it could look like (just the "Old", "Good new" and "Disabled" ignore the other ones):
mockup

### PR DESCRIPTION
**Pull request by susnux**
### ☑️ Resolves

* Resolves #4126 

The inner label is now visible, to disable any label set `label-outside` to true, `label-visible` property is removed.
The label is shown instead of the placeholder if the input is empty and not focused, when focused the label is moved up and scaled but always shown.

Also the action input is adjusted for this change.

#### NcInputField
new

#### NcActionInput
new-action

### 🚧 Tasks

- Maybe adjust the datetime picker to this changes in a followup, @nextcloud/designers ?

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Comment by dartcafe** [comment]
I like it, but shouldn't there be a style guide to prevent, that every developer just follows his personal preference?

@ChristophWurst

**Review by marcoambrosini — COMMENTED** [review]
@susnux  I still think that the label should move on the border as this will conflict with leading icons like search can we still change this?

**Comment by susnux** [comment]
@marcoambrosini sure, I just got not much time to adjust this here, but it is still on my list :)

**Review by st3iny — COMMENTED** [review]
Looks good to me. Is there anything left to be done/discussed?

**Comment by susnux** [comment]
@marcoambrosini 
>  I still think that the label should move on the border as this will conflict with leading icons like search can we still change this?

I created an alternative with the label inside the border here: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394 . So you can compare both on the preview deployments.

I personally think that the label within the border is cleaner, is allows to have multiple input elements (input field, buttons, NcSelect) side by side and all having the same "border-height".
Also I do not think that the label conflicts with the icon, as the label will always be shorter (due to font size) when shown above than on initial state.

But this is a decision for designers :)

**Comment by AndyScherzinger** [comment]
Label on the border would also match Material Design 2 and 3 btw which seems to be what we usually try to use or be inspired by.

**Comment by susnux** [comment]
Close in favor of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394

**Pull request closed without merging**
