### PR TITLE
Add header prop to NcRelatedResourcesPanel

### PR DESCRIPTION
**Pull request by GretaD**
### ☑️ Resolves

* Needed for https://github.com/nextcloud/contacts/issues/3364

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A
related_before | Screenshot from 2023-10-27 14-33-16

### 🚧 Tasks

- [x] There are many ways how to do this, but for now we only need the app header to be dynamic so each one of the apps can add their own.

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Comment by szaimen** [comment]
What happened here?
image

**Comment by GretaD** [comment]
my lint:fix likes it that way, looks like

**Comment by szaimen** [comment]
Weird

**Comment by skjnldsv** [comment]
Please set appropriate `fix` or `enhancement` labels next time :+1:

**Pull request merged**
