### PR TITLE
fix: japanese system tags translation

### PR DESCRIPTION
**Pull request by hamza221**
### ☑️ Resolves

- Fix #…

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🚧 Tasks

- [x] ...

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Review by Antreesy — COMMENTED** [review]
Haven't found any other broken strings, so should be good to go

**Review by Antreesy — APPROVED** [review]

**Comment by susnux** [comment]
This will be directly overwritten again by transifex.
Instead you need to fix this on transifex directly

**Comment by Antreesy** [comment]
`To translate you need to be logged in and a member of the Japanese (Japan) team`

Maybe ask community chat? :https://cloud.nextcloud.com/call/xhz52vhg

**Comment by hamza221** [comment]
done 
image

**Review by susnux — APPROVED** [review]

**Comment by ShGKme** [comment]
Won't it be reverted by any translation update from transifex? Why change from here?

**Comment by susnux** [comment]
> Won't it be reverted by any translation update from transifex? Why change from here?

Customer issue. We need a fix now and even if it is fixed on transifex since 4 days it is not synced back to this repo

**Pull request merged**
