### PR TITLE
Fix a visual bug in Nextcloud 25 "select"

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

The problem :

### CODE REVIEW

**Comment by Pytal** [comment]
Which app does this appear in @Jerome-Herbinet?

**Comment by Jerome-Herbinet** [comment]
> Which app does this appear in @Jerome-Herbinet?

I.e. Contacts' files and personnal schedule settings (Groupware availability).

**Comment by Pytal** [comment]
I cannot reproduce this on `stable25`

image

What steps are needed to reproduce this @Jerome-Herbinet?

**Comment by Jerome-Herbinet** [comment]
> I cannot reproduce this on `stable25`
> 
> image
> 
> What steps are needed to reproduce this @Jerome-Herbinet?

"Contacts" files for example :

**Comment by Pytal** [comment]
Reproduces when setting the language to French

Seems to be the placeholder https://github.com/nextcloud/contacts/blob/b7c8b16f1e2b99122663408995c3730798e582b3/src/components/Properties/PropertyText.vue#L35 which is force shown by design in https://github.com/nextcloud/nextcloud-vue/blob/10982969daa388aa3fb16fbf88b4055335016f7a/src/components/NcMultiselect/index.scss#L148-L153 which are custom overrides of the styles from https://github.com/shentao/vue-multiselect

Need input from the developer, any ideas @skjnldsv?

**Comment by skjnldsv** [comment]
> Need input from the developer, any ideas @skjnldsv?

Too far away from this app now, I would forward to the groupware team

**Comment by ChristophWurst** [comment]
The question is about the multiselect, not groupware @skjnldsv.

Related https://github.com/nextcloud/contacts/issues/2971 / https://github.com/nextcloud/contacts/pull/3007

**Comment by raimund-schluessler** [comment]
The `NcMultiselect` component was deprecated and got removed in master now. In case you think this still needs a fix for older versions, please recreate this PR against the `stable7` branch.

**Pull request closed without merging**
