### PR TITLE
Make package ESM by default

### PR DESCRIPTION
**Pull request by susnux**
### ☑️ Resolves

* <del>Supersedes #4930</del>
* Fixes the issue in #4947

This makes the package using ESM by default (`type: "module"`) and adjusts all scripts used.
Some stuff like stylelint and eslint do not work correctly with ESM yet, so they are kept as commonjs scripts.

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Comment by susnux** [comment]
Basically this works and simplifies the code base, but it does not fix the Typescript issue

**Review by ShGKme — APPROVED** [review]

**Review by raimund-schluessler — APPROVED** [review]

**Comment by susnux** [comment]
Do we want this for v8 or should I change the target branch to `next` for v9?

**Comment by ShGKme** [comment]
> Do we want this for v8 or should I change the target branch to `next` for v9?

I think this is fine for v8. It should not affect the distributive and works fine on Server. Probably, we should test on more apps before just in case, e.g., Talk.

**Comment by ShGKme** [comment]
Talk works including calls

**Comment by skjnldsv** [comment]
> I think this is fine for v8. It should not affect the distributive and works fine on Server. Probably, we should test on more apps before just in case, e.g., Talk.

Switching package types is a breaking change, even if that does not break on our ecosystem :)
So v9 it is pls

**Comment by ShGKme** [comment]
> Switching package types is a breaking change, even if that does not break on our ecosystem :)

Why?

**Comment by skjnldsv** [comment]
> What does this change break?

The module resolution changes.
Pre-processors will now treat this package as `module`, not saying this will cause issues on our ecosystem, but I'm saying this is no patch release (and arguably, no minor either)

**Comment by susnux** [comment]
Merged into Next for reasons mentioned by @skjnldsv

**Pull request merged**
