### PR TITLE
fix: Adjust license in `package.json`

### PR DESCRIPTION
**Pull request by susnux**
### ☑️ Resolves

We are using AGPL-3.0 or later, so adjust the package.json to reflect this

### CODE REVIEW

**Review by ShGKme — COMMENTED** [review]
I might be wrong, but I though it is not valid to change 3.0 to 3-or-later... cc @nickvergessen

**Review by ShGKme — COMMENTED** [review]
I might be wrong, but I though it is not valid to change 3.0 to 3-or-later... cc @nickvergessen

**Comment by susnux** [comment]
@ShGKme relicensing is not possible without asking every contributor (if they are from community). But this is not re-licensing the library but fixing it. Every file in the source is AGPL-3.0-or-later, there is no AGPL-3.0 (or correctly AGPL-3.0-only) file.

**Comment by ShGKme** [comment]
> Every file in the source is AGPL-3.0-or-later

Indeed. Except the `LICENSE` root file

**Review by ShGKme — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
> Every file in the source is AGPL-3.0-or-later

Except the `package(-lock).json` :see_no_evil:

**Comment by ShGKme** [comment]
> Except the `package(-lock).json` 🙈

Does it actually have its own license? Not the `license` property which determines the package license (and where `AGPL-3.0` also means `AGPL-3.0-or-later`)

**Comment by skjnldsv** [comment]
> Does it actually have its own license?

I would (maybe wrongly) assume that every file have its own license anyway :thinking:

**Pull request merged**
