### PR TITLE
feat: introduce `useIsMobile` and `useIsFullscreen` composables

### PR DESCRIPTION
**Pull request by ShGKme**
Both composables store and return reactive state in module-scope (aka global) and are updated on resize.

Old mixins are now using new composables and are marked `deprecated`.

**Fully compatible with Vue 3**

Usage example in Options API:
```vue
<script>
import { useIsMobile } from '@nextcloud/vue/dist/Composables/useIsMobile.js'

export default {
  setup() {
    return {
      isMobile: useIsMobile(),
    }
  },

  watch: {
    isMobile() {
      // handle
    },
  },
}
</script>

<template>
  <div v-if="isMobile">I'm on mobile</div>
</template>
```

### 🚧 Tasks

- [x] Add `useIsMobile` composable, that stores and returns `isMobile` state in module-scope (aka global)
- [x] Add composables to build
- [x] Refactor `isMobile` mixin to use new composable and mark deprecated
- [x] Migrate all components to use composable instead of the mixin
- [x] The same with `isFullscreen`

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Comment by ShGKme** [comment]
P.S. It was originally discussed in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4758

**Comment by raimund-schluessler** [comment]
@ShGKme Awesome, thanks a lot. Works well!

**Review by raimund-schluessler — APPROVED** [review]

**Review by susnux — APPROVED** [review]
Finally got some time for testing: Works nicely :rocket:

**Comment by susnux** [comment]
BTW for the tests you need to adjust the import in `tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js`

**Comment by raimund-schluessler** [comment]
@ShGKme I rebased and adjusted the tests of `NcAppNavigation`. I hope, that's ok for you.

**Comment by raimund-schluessler** [comment]
@ShGKme Can we go ahead here? I didn't want to merge your PR without you agreeing to it :wink:

**Pull request merged**
