### PR TITLE
fix(NcEmojiPicker): adjust hover effects to new design

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

- Fix hover effects on emoji buttons
- Added fallback for Nextcloud <= v29

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
2024-09-05_19h18_50 | 2024-09-05_19h18_24

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Comment by susnux** [comment]
I am not sure but was there not a design review call where it was said that round outline makes sense for emoji?

**Comment by ShGKme** [comment]
I'd keep it rounded

**Review by marcoambrosini — APPROVED** [review]

**Comment by marcoambrosini** [comment]
@susnux @ShGKme I think they look fine less rounded, like the reaction buttons in talk right now

**Review by susnux — APPROVED** [review]
I really do not care, both are fine. Noticed that e.g. messengers like Telegram also have "angular" hover effect.
Changes are clean :+1: 

(To cite a user I asked: "IPhone users would prefer the round one, Android users the angular one.")

**Pull request merged**
